from enum import Enum

class ResponseSignal(Enum):

    FILE_VALIDATION_FAILED = "FILE_VALIDATION_FAILED"
    FILE_VALIDATION_SUCCESS = "FILE_VALIDATION_SUCCESS"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FIlE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDS_LIMIT = "FILE_SIZE_EXCEEDS_LIMIT"
    PROCESSING_SUCCESS = "processing_success"
    PROCESSING_FAILED = "processing_failed"